"""Generate the §5 notebook.

One notebook lives in this directory:

- ``section_5.ipynb`` — mode-toggled (interactive vs preload), per-section
  cells, multi-model comparison at the bottom.

Cells are defined as plain strings so the notebook content is reviewable
in version control.

Usage:
    python notebooks/build_notebooks.py
"""
import json
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }


NB_META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.10"},
}


def write_nb(name: str, cells: list) -> None:
    out = NB_DIR / name
    nb = {"cells": cells, "metadata": NB_META, "nbformat": 4, "nbformat_minor": 5}
    out.write_text(json.dumps(nb, indent=1))
    print(f"  wrote {out}  ({len(cells)} cells)")


# ════════════════════════════════════════════════════════════════════════════
# section_5.ipynb
# ════════════════════════════════════════════════════════════════════════════

cells = []

# ── Title ───────────────────────────────────────────────────────────────
cells.append(md(
    "# Section 5 — Activation-Level Experiments\n",
    "\n",
    "Two modes via a single toggle:\n",
    "\n",
    "- `MODE = 'interactive'` — load a model into the kernel (one cell), then run each §5\n",
    "  experiment in-memory cell by cell. Fast iteration, kernel-resident model.\n",
    "  Useful for exploration, tweaking parameters, and seeing intermediate state.\n",
    "  Not bit-exact to the canonical scripts (small differences in loop scoping).\n",
    "\n",
    "- `MODE = 'preload'` — read pre-generated JSON results from a directory. No model\n",
    "  load, no GPU. Used when you've already run the canonical scripts (e.g. via\n",
    "  `run_section_5.py` or `run_llama_n1000.sh`) and just want to render figures.\n",
    "  Bit-exact to the paper.\n",
    "\n",
    "The **multi-model comparison** section at the bottom is always preload-mode\n",
    "(loading three 8B models simultaneously is too heavy). It takes a dict of\n",
    "results paths and renders the cross-model figures.\n",
))

# ── Setup ───────────────────────────────────────────────────────────────
cells.append(code(
    "# ── Setup ───────────────────────────────────────────────────────────\n",
    "import sys, os, json, math, gc, time\n",
    "from pathlib import Path\n",
    "from collections import defaultdict\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "REPO = Path.cwd()\n",
    "while not (REPO / 'activation_robustness').exists() and REPO != REPO.parent:\n",
    "    REPO = REPO.parent\n",
    "assert (REPO / 'activation_robustness').exists(), 'Run from repo root or notebooks/.'\n",
    "sys.path.insert(0, str(REPO))\n",
    "os.chdir(REPO)\n",
    "\n",
    "FIGURES_DIR = REPO / 'figures'\n",
    "FIGURES_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "matplotlib.rcParams.update({\n",
    "    'font.size': 11, 'axes.titlesize': 12, 'axes.labelsize': 11,\n",
    "    'legend.fontsize': 9, 'figure.dpi': 150,\n",
    "})\n",
    "\n",
    "def cos_to_deg(c):\n",
    "    return math.degrees(math.acos(max(-1.0, min(1.0, c))))\n",
    "\n",
    "def cos_std_to_deg_std(mu, sigma):\n",
    "    a = math.acos(max(-1.0, min(1.0, mu)))\n",
    "    s = math.sin(a)\n",
    "    return math.degrees(sigma / s) if s > 1e-6 else 0.0\n",
    "\n",
    "def angular(a, b):\n",
    "    na, nb = np.linalg.norm(a), np.linalg.norm(b)\n",
    "    cos = max(-1.0, min(1.0, float(np.dot(a, b) / (na * nb))))\n",
    "    return math.degrees(math.acos(cos))\n",
    "\n",
    "def n_layers(per_layer): return max(int(k) for k in per_layer) + 1\n",
    "\n",
    "def load_json(path):\n",
    "    p = Path(path)\n",
    "    return json.load(open(p)) if p.exists() else None\n",
    "\n",
    "print(f'REPO: {REPO}')\n",
))

# ── Mode + config ───────────────────────────────────────────────────────
cells.append(md(
    "## Mode & configuration\n",
    "\n",
    "Set `MODE` and (depending on mode) the relevant variables. Re-run all cells\n",
    "below to switch modes.\n",
))

cells.append(code(
    "# ── Mode & configuration ────────────────────────────────────────────\n",
    "MODE = 'preload'         # 'interactive' | 'preload'\n",
    "\n",
    "# Interactive mode:\n",
    "MODEL = 'llama'          # 'llama' | 'qwen3' | 'gemma'\n",
    "N     = 30               # prompts per condition (small for quick demo)\n",
    "\n",
    "# Preload mode:\n",
    "RESULTS_DIR = REPO / 'activation_robustness' / 'results'\n",
    "\n",
    "# ────────────────────────────────────────────────────────────────────\n",
    "MODEL_CONFIG = {\n",
    "    'llama':  {'name': 'meta-llama/Llama-3.1-8B-Instruct', 'layers': [8, 16, 24, 31]},\n",
    "    'qwen3':  {'name': 'Qwen/Qwen3-8B',                   'layers': [9, 18, 27, 35]},\n",
    "    'gemma':  {'name': 'google/gemma-4-E4B-it',           'layers': [10, 21, 28, 29, 40, 41]},\n",
    "}\n",
    "\n",
    "print(f'MODE: {MODE}')\n",
    "if MODE == 'interactive':\n",
    "    print(f'  MODEL: {MODEL}  ({MODEL_CONFIG[MODEL][\"name\"]})')\n",
    "    print(f'  N:     {N}')\n",
    "elif MODE == 'preload':\n",
    "    print(f'  RESULTS_DIR: {RESULTS_DIR}')\n",
    "else:\n",
    "    raise ValueError(f'unknown MODE: {MODE!r}')\n",
))

# ── Model load (interactive only) ───────────────────────────────────────
cells.append(md(
    "## Load model into kernel (interactive mode only)\n",
    "\n",
    "This cell loads the chosen model once into the notebook kernel. All subsequent\n",
    "interactive-mode cells will reuse `model`, `tokenizer`, `device` from the kernel.\n",
    "Skipped under preload mode.\n",
))

cells.append(code(
    "# ── Model load (interactive only) ───────────────────────────────────\n",
    "if MODE == 'interactive':\n",
    "    import torch\n",
    "    from activation_robustness.analysis.extraction import load_hf_model, format_prompt\n",
    "    from activation_robustness.perturbations.typo import AdjacentKey\n",
    "    from activation_robustness.perturbations.omission import MissingSpace\n",
    "    from activation_robustness.perturbations import get_by_name\n",
    "    from activation_robustness.data.external import sample_openorca\n",
    "\n",
    "    cfg = MODEL_CONFIG[MODEL]\n",
    "    print(f\"Loading {cfg['name']} ...\")\n",
    "    model, tokenizer = load_hf_model(cfg['name'], dtype='bfloat16')\n",
    "    device = next(model.parameters()).device\n",
    "    LAYERS = cfg['layers']\n",
    "    print(f'Model loaded on {device}.')\n",
    "    print(f'Checkpoint layers: {LAYERS}')\n",
    "else:\n",
    "    print(f'Skipped (MODE = {MODE!r}).')\n",
))

# ── §5.1 On-site rotation ───────────────────────────────────────────────
cells.append(md(
    "## §5.1 — On-site rotation (Figure 1)\n",
    "\n",
    "Apply a single adjacent-key typo, measure the angular rotation of the hidden state\n",
    "at the typo's token position. Paper §5.1 reports 43°–56° across all three models\n",
    "(N=100 OpenOrca prompts).\n",
    "\n",
    "**Interactive mode:** small-N (=N) demonstration using the kernel-resident model.\n",
    "**Preload mode:** reads the per-model `per_layer_same_pos` JSON from `RESULTS_DIR`.\n",
))

cells.append(code(
    "# ── §5.1 — On-site rotation ─────────────────────────────────────────\n",
    "PER_MODEL_RESULTS = {\n",
    "    'llama':  RESULTS_DIR / 'per_layer_same_pos_100' / 'results.json',\n",
    "    'qwen3':  RESULTS_DIR / 'qwen3_8b' / 'per_layer_same_pos' / 'results.json',\n",
    "    'gemma':  RESULTS_DIR / 'gemma4_e4b' / 'per_layer_same_pos' / 'results.json',\n",
    "}\n",
    "\n",
    "if MODE == 'interactive':\n",
    "    # In-kernel demonstration: small N, using helpers + kernel model.\n",
    "    rng = np.random.default_rng(49)\n",
    "    adj_key = AdjacentKey()\n",
    "    prompts = sample_openorca(n_per_bucket=N, buckets={'100-300': (100, 300)}, seed=49)\n",
    "    angles_per_layer = {L: [] for L in LAYERS}\n",
    "    for prompt in prompts[:N]:\n",
    "        text = prompt['text']\n",
    "        fc = format_prompt(tokenizer, text)\n",
    "        ic = tokenizer.encode(fc)\n",
    "        # Extract clean activations for all chosen layers\n",
    "        ids_t = tokenizer(fc, return_tensors='pt').input_ids.to(device)\n",
    "        with torch.no_grad():\n",
    "            o = model(ids_t, output_hidden_states=True)\n",
    "        h_clean = {L: o.hidden_states[L + 1][0].float().cpu().numpy().astype(np.float64) for L in LAYERS}\n",
    "        # For each typo: extract perturbed and measure\n",
    "        vs = adj_key.enumerate_all(text); rng.shuffle(vs)\n",
    "        n_used = 0\n",
    "        for pt, m in vs[:8]:\n",
    "            fp = format_prompt(tokenizer, pt)\n",
    "            ip = tokenizer.encode(fp)\n",
    "            if len(ic) != len(ip): continue\n",
    "            diffs = [i for i, (a, b) in enumerate(zip(ic, ip)) if a != b]\n",
    "            if len(diffs) != 1: continue\n",
    "            ids_p = tokenizer(fp, return_tensors='pt').input_ids.to(device)\n",
    "            with torch.no_grad():\n",
    "                op = model(ids_p, output_hidden_states=True)\n",
    "            for L in LAYERS:\n",
    "                hp_L = op.hidden_states[L + 1][0, diffs[0]].float().cpu().numpy().astype(np.float64)\n",
    "                angles_per_layer[L].append(angular(h_clean[L][diffs[0]], hp_L))\n",
    "            n_used += 1\n",
    "            if n_used >= 4: break\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "    means = [np.mean(angles_per_layer[L]) for L in LAYERS]\n",
    "    stds  = [np.std(angles_per_layer[L])  for L in LAYERS]\n",
    "    ns    = [len(angles_per_layer[L])     for L in LAYERS]\n",
    "    ax.errorbar(LAYERS, means, yerr=stds, fmt='o-', linewidth=2, capsize=3)\n",
    "    ax.set_xlabel('Layer')\n",
    "    ax.set_ylabel('On-site angular change (°)')\n",
    "    ax.set_title(f'{MODEL.title()} on-site rotation, N≈{ns[-1]} typo measurements')\n",
    "    ax.set_ylim(20, 80); ax.grid(alpha=0.3)\n",
    "    plt.tight_layout(); plt.show()\n",
    "    for L, m, s, n in zip(LAYERS, means, stds, ns):\n",
    "        print(f'  L{L}: {m:.1f}° ± {s:.1f}°  (N={n})')\n",
    "\n",
    "elif MODE == 'preload':\n",
    "    # Render Figure 1: cross-model on-site rotation, overlaying any model\n",
    "    # whose per_layer_same_pos JSON exists.\n",
    "    CHECKPOINT_LAYERS = {\n",
    "        'Llama-3.1-8B': [8, 16, 24, 31],\n",
    "        'Qwen3-8B':     [9, 18, 27, 35],\n",
    "        'Gemma-4-E4B':  [10, 21, 28, 29, 40, 41],\n",
    "    }\n",
    "    GEMMA_SLIDING = {28, 40}\n",
    "    COLORS  = {'Llama-3.1-8B': '#2563eb', 'Qwen3-8B': '#16a34a', 'Gemma-4-E4B': '#dc2626'}\n",
    "    MARKERS = {'Llama-3.1-8B': 'o',       'Qwen3-8B': 's',       'Gemma-4-E4B': '^'}\n",
    "    NICE = {'llama': 'Llama-3.1-8B', 'qwen3': 'Qwen3-8B', 'gemma': 'Gemma-4-E4B'}\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "    shown = []\n",
    "    for key, path in PER_MODEL_RESULTS.items():\n",
    "        data = load_json(path)\n",
    "        if data is None:\n",
    "            continue\n",
    "        pl = data.get('per_layer') or data.get('per_layer_same_pos', {}).get('per_layer')\n",
    "        if pl is None: continue\n",
    "        mname = NICE[key]\n",
    "        total = n_layers(pl)\n",
    "        layers = CHECKPOINT_LAYERS[mname]\n",
    "        depth  = [round(L / (total - 1) * 100) for L in layers]\n",
    "        angles = [cos_to_deg(pl[str(L)]['same_pos_mean']) for L in layers]\n",
    "        stds   = [cos_std_to_deg_std(pl[str(L)]['same_pos_mean'], pl[str(L)]['same_pos_std']) for L in layers]\n",
    "        ax.plot(depth, angles, marker=MARKERS[mname], markersize=7, color=COLORS[mname], label=mname, linewidth=2)\n",
    "        ax.fill_between(depth, [a - s for a, s in zip(angles, stds)], [a + s for a, s in zip(angles, stds)],\n",
    "                        color=COLORS[mname], alpha=0.15)\n",
    "        if mname == 'Gemma-4-E4B':\n",
    "            for L, dp, ang in zip(layers, depth, angles):\n",
    "                if L in GEMMA_SLIDING:\n",
    "                    ax.plot(dp, ang, marker=MARKERS[mname], markersize=9,\n",
    "                            markerfacecolor='white', markeredgecolor=COLORS[mname], markeredgewidth=2)\n",
    "        shown.append(mname)\n",
    "    ax.set_xlabel('Layer depth (%)')\n",
    "    ax.set_ylabel('On-site angular change (°)')\n",
    "    ax.set_ylim(20, 80); ax.legend() if shown else None; ax.grid(alpha=0.3)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(FIGURES_DIR / 'fig_onsite_crossmodel.png', bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Models on figure: {shown}')\n",
))

# ── §5.2 Spatial decay ──────────────────────────────────────────────────
cells.append(md(
    "## §5.2 — Spatial decay (Figure 2)\n",
    "\n",
    "Relative angular change as a function of distance downstream of the typo.\n",
    "Paper §5.2 reports decay below 15% within ~10 tokens (Llama, layers 8/16/24/31).\n",
    "\n",
    "**Interactive mode:** decay curves on N prompts using the kernel model.\n",
    "**Preload mode:** reads `typo_decay_preamble_control` (Llama) plus `qwen3_8b/long_decay`\n",
    "and `gemma4_e4b/long_decay` if present.\n",
))

cells.append(code(
    "# ── §5.2 — Spatial decay ────────────────────────────────────────────\n",
    "if MODE == 'interactive':\n",
    "    rng2 = np.random.default_rng(43)\n",
    "    adj_key = AdjacentKey()\n",
    "    long_prompts = sample_openorca(n_per_bucket=N, buckets={'200-500': (200, 500)}, seed=43)\n",
    "    D_MAX = 30\n",
    "    curves = {L: [] for L in LAYERS}\n",
    "    for prompt in long_prompts[:N]:\n",
    "        text = prompt['text']\n",
    "        fc = format_prompt(tokenizer, text); ic = tokenizer.encode(fc)\n",
    "        vs = adj_key.enumerate_all(text); rng2.shuffle(vs)\n",
    "        ids_t = tokenizer(fc, return_tensors='pt').input_ids.to(device)\n",
    "        with torch.no_grad():\n",
    "            o = model(ids_t, output_hidden_states=True)\n",
    "        h_clean = {L: o.hidden_states[L + 1][0].float().cpu().numpy().astype(np.float64) for L in LAYERS}\n",
    "        for pt, m in vs[:1]:\n",
    "            fp = format_prompt(tokenizer, pt); ip = tokenizer.encode(fp)\n",
    "            if len(ic) != len(ip): continue\n",
    "            diffs = [i for i, (a, b) in enumerate(zip(ic, ip)) if a != b]\n",
    "            if len(diffs) != 1: continue\n",
    "            tp = diffs[0]\n",
    "            ids_p = tokenizer(fp, return_tensors='pt').input_ids.to(device)\n",
    "            with torch.no_grad():\n",
    "                op = model(ids_p, output_hidden_states=True)\n",
    "            d_max_here = min(D_MAX + 1, h_clean[LAYERS[0]].shape[0] - tp)\n",
    "            for L in LAYERS:\n",
    "                hp_L = op.hidden_states[L + 1][0].float().cpu().numpy().astype(np.float64)\n",
    "                rel = []\n",
    "                base = angular(h_clean[L][tp], hp_L[tp])\n",
    "                if base < 1e-3: continue\n",
    "                for d in range(d_max_here):\n",
    "                    rel.append(angular(h_clean[L][tp + d], hp_L[tp + d]) / base)\n",
    "                curves[L].append(rel)\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "    color_map = {LAYERS[0]: '#93c5fd', LAYERS[1]: '#3b82f6', LAYERS[2]: '#1d4ed8', LAYERS[3]: '#1e3a5f'}\n",
    "    for L in LAYERS[:4]:\n",
    "        if not curves[L]: continue\n",
    "        n_min = min(len(c) for c in curves[L])\n",
    "        avg = np.mean([c[:n_min] for c in curves[L]], axis=0)\n",
    "        ax.plot(range(1, n_min), avg[1:], color=color_map[L], lw=2.0, label=f'Layer {L}')\n",
    "    ax.axhline(0.10, color='#94a3b8', lw=1, ls='--', alpha=0.7, label='10% ref')\n",
    "    ax.set_xscale('log'); ax.set_yscale('log')\n",
    "    ax.set_xlim(1, 30); ax.set_ylim(0.03, 1.1)\n",
    "    ax.set_xlabel('Distance from typo (tokens)')\n",
    "    ax.set_ylabel('Relative angular change')\n",
    "    ax.set_title(f'{MODEL.title()} spatial decay, N={N}')\n",
    "    ax.legend(framealpha=0.9, fontsize=9, loc='upper right')\n",
    "    ax.grid(True, which='major', alpha=0.25); ax.grid(True, which='minor', alpha=0.1)\n",
    "    plt.tight_layout(); plt.show()\n",
    "\n",
    "elif MODE == 'preload':\n",
    "    pc = load_json(RESULTS_DIR / 'typo_decay_preamble_control' / 'results.json')\n",
    "    if pc is None:\n",
    "        print('skip: typo_decay_preamble_control/results.json missing')\n",
    "    else:\n",
    "        LAYERS_PC = ['8', '16', '24', '31']\n",
    "        LAYER_COLORS = {'8': '#93c5fd', '16': '#3b82f6', '24': '#1d4ed8', '31': '#1e3a5f'}\n",
    "        D_MAX = 30\n",
    "        d_vals = list(range(1, D_MAX + 1))\n",
    "        CONDITIONS = [c for c in ['early', 'mid', 'late'] if c in pc.get('per_condition', {})]\n",
    "\n",
    "        fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "        for lyr in LAYERS_PC:\n",
    "            curves = []\n",
    "            for cond in CONDITIONS:\n",
    "                e = pc['per_condition'][cond]['per_layer'].get(lyr)\n",
    "                if e: curves.append([e['avg_rel_curve'][d] for d in d_vals])\n",
    "            if curves:\n",
    "                ax.plot(d_vals, np.mean(curves, axis=0), color=LAYER_COLORS[lyr], lw=2.0, label=f'Layer {lyr}')\n",
    "        ax.axhline(0.10, color='#94a3b8', lw=1, ls='--', alpha=0.7, label='10% ref')\n",
    "        ax.set_xscale('log'); ax.set_yscale('log')\n",
    "        ax.set_xlim(1, D_MAX); ax.set_ylim(0.03, 1.1)\n",
    "        ax.set_xlabel('Distance from typo (tokens)')\n",
    "        ax.set_ylabel('Relative angular change')\n",
    "        ax.legend(framealpha=0.9, loc='upper right', fontsize=9)\n",
    "        ax.grid(True, which='major', alpha=0.25); ax.grid(True, which='minor', alpha=0.1)\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(FIGURES_DIR / 'fig_spatial_decay.png', bbox_inches='tight')\n",
    "        plt.show()\n",
))

# ── §5.3 Two-typo (Llama only) ──────────────────────────────────────────
cells.append(md(
    "## §5.3 — Two co-occurring typos (Figure 3) — Llama only\n",
    "\n",
    "Combined-perturbation curve vs single-typo-A baseline at three inter-typo distances.\n",
    "**Interactive mode** shows a small-N approximation; the canonical script\n",
    "(`multi_typo_vanilla.py`) covers the three distance buckets fully.\n",
))

cells.append(code(
    "# ── §5.3 — Two-typo accumulation (Fig 3) ────────────────────────────\n",
    "if MODE == 'interactive':\n",
    "    print('Interactive mode for §5.3 (two-typo) is non-trivial — the canonical script')\n",
    "    print('handles three distance buckets with careful re-pairing logic.')\n",
    "    print('Run `python activation_robustness/experiments/multi_typo_vanilla.py --n-prompts N`')\n",
    "    print('then re-run this notebook in MODE = preload to see Figure 3.')\n",
    "elif MODE == 'preload':\n",
    "    mv = load_json(RESULTS_DIR / 'multi_typo_vanilla' / 'results.json')\n",
    "    if mv is None or 'two_typo' not in mv:\n",
    "        print('skip: multi_typo_vanilla/results.json missing')\n",
    "    else:\n",
    "        tt = mv['two_typo']\n",
    "        CONDS = [\n",
    "            ('very_close_1-4', '#C44E52', 'd ≈ 2  (close)'),\n",
    "            ('medium_10-20',   '#2563eb', 'd ≈ 15 (medium)'),\n",
    "            ('mid_far_20-30',  '#16a34a', 'd ≈ 25 (separated)'),\n",
    "        ]\n",
    "        avail = [c for c in CONDS if c[0] in tt]\n",
    "        if avail:\n",
    "            X_START, X_MAX = 1, 60\n",
    "            xs = np.arange(X_START, X_MAX)\n",
    "            t2_ref = np.mean([np.array(tt[b]['avg_t2_angular'][X_START:X_MAX]) for b, _, _ in avail], axis=0)\n",
    "            fig, ax = plt.subplots(figsize=(6.0, 4.2))\n",
    "            ax.plot(xs, t2_ref, color='#94a3b8', lw=1.4, ls='--', label='single typo  (typo-A only)')\n",
    "            for bucket, color, label in avail:\n",
    "                ax.plot(xs, np.array(tt[bucket]['avg_comb_angular'][X_START:X_MAX]), color=color, lw=2.0, label=label)\n",
    "            ax.set_xlabel('Offset from typo-A (tokens)'); ax.set_ylabel('Angular change (°)')\n",
    "            ax.set_xlim(X_START, X_MAX - 1); ax.set_ylim(0, 40)\n",
    "            ax.legend(framealpha=0.9, fontsize=9, loc='upper right')\n",
    "            ax.grid(axis='y', alpha=0.3, lw=0.7)\n",
    "            ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)\n",
    "            plt.tight_layout()\n",
    "            plt.savefig(FIGURES_DIR / 'fig_multi_typo.png', bbox_inches='tight')\n",
    "            plt.show()\n",
))

# ── Table 1 (Llama only) ────────────────────────────────────────────────
cells.append(md(
    "## §5.3 — Perturbation type survey (Table 1) — Llama only\n",
    "\n",
    "EOT angular change for four perturbation types, expressed as a percentage of the\n",
    "between-prompt baseline (~34.6°). **Preload mode** reads `multi_perturbation_eot`\n",
    "and `eot_baseline_variance` JSONs.\n",
))

cells.append(code(
    "# ── §5.3 — Perturbation type survey (Table 1) ───────────────────────\n",
    "if MODE == 'interactive':\n",
    "    print('Interactive Table 1 reproduction requires running 4 perturbation types')\n",
    "    print('against question-prompts + non-question prompts. Run instead:')\n",
    "    print('  python activation_robustness/experiments/multi_perturbation_eot.py --n-per-bucket N')\n",
    "    print('  python activation_robustness/experiments/eot_baseline_variance.py')\n",
    "elif MODE == 'preload':\n",
    "    mpe  = load_json(RESULTS_DIR / 'multi_perturbation_eot' / 'results.json')\n",
    "    bvar = load_json(RESULTS_DIR / 'eot_baseline_variance' / 'results.json')\n",
    "    if mpe is None:\n",
    "        print('skip: multi_perturbation_eot/results.json missing')\n",
    "    else:\n",
    "        L = 31\n",
    "        bp = []\n",
    "        if bvar is not None:\n",
    "            for bd in bvar.values():\n",
    "                if isinstance(bd, dict) and f'L{L}' in bd:\n",
    "                    bp.append(bd[f'L{L}']['within_angle_mean'])\n",
    "        baseline = float(np.mean(bp)) if bp else 34.6\n",
    "        print(f'Between-prompt baseline (L{L}): {baseline:.1f}°')\n",
    "        print()\n",
    "        print(f'{\"Perturbation\":<28}{\"d\":>3}  {\"EOT angle\":>10}  {\"% baseline\":>11}')\n",
    "        print('-' * 60)\n",
    "        rows = [\n",
    "            ('Adjacent-key',    'd10', ['adjacent_key_d10']),\n",
    "            ('Missing space',   'd10', ['missing_space_d10']),\n",
    "            ('Question→period', 'd1',  ['question_to_period_d1']),\n",
    "            ('Question→/',      'd1',  ['question_to_slash_d1']),\n",
    "        ]\n",
    "        table = mpe.get('table') or mpe.get('summary') or mpe\n",
    "        for label, d, keys in rows:\n",
    "            found = None\n",
    "            for k in keys:\n",
    "                for src in (table.get(k, {}), mpe.get('per_perturbation', {}).get(k, {})):\n",
    "                    if isinstance(src, dict):\n",
    "                        ang = src.get('angle_mean') or src.get(f'L{L}', {}).get('angle_mean')\n",
    "                        if ang: found = ang; break\n",
    "                if found is not None: break\n",
    "            if found is None:\n",
    "                print(f'{label:<28}{d:>3}  {\"(missing)\":>10}  {\"\":>11}')\n",
    "            else:\n",
    "                print(f'{label:<28}{d:>3}  {found:>9.1f}°  {(100*found/baseline):>9.0f}%')\n",
    "        print('-' * 60)\n",
    "        print(f'{\"Between-prompt baseline\":<28}{\"---\":>3}  {baseline:>9.1f}°  {\"100%\":>11}')\n",
))

# ── Punctuation decay (Llama only) ──────────────────────────────────────
cells.append(md(
    "## Appendix — Decay-shape invariance to perturbation severity — Llama only\n",
    "\n",
    "Compares AdjacentKey decay against terminal-punctuation perturbations on Llama L31.\n",
))

cells.append(code(
    "# ── Punct-decay appendix figure ─────────────────────────────────────\n",
    "if MODE == 'interactive':\n",
    "    print('Run: python activation_robustness/experiments/punct_decay_control.py --n-prompts N')\n",
    "    print('(needs ≥ 20 question-prompts) then re-render in preload mode.')\n",
    "elif MODE == 'preload':\n",
    "    pdd = load_json(RESULTS_DIR / 'punct_decay_control' / 'results.json')\n",
    "    tdd = load_json(RESULTS_DIR / 'typo_decay_preamble_control' / 'results.json')\n",
    "    if pdd is None or tdd is None:\n",
    "        print('Need both punct_decay_control and typo_decay_preamble_control results.')\n",
    "    else:\n",
    "        D_MAX = pdd.get('decay_window', 30)\n",
    "        d_vals = list(range(1, D_MAX))\n",
    "        ak     = tdd['per_condition']['mid']['per_layer']['31']['avg_rel_curve'][:D_MAX]\n",
    "        period = pdd['per_condition']['period']['per_layer']['31']['avg_rel_curve']\n",
    "        slash  = pdd['per_condition']['slash']['per_layer']['31']['avg_rel_curve']\n",
    "\n",
    "        fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "        ax.plot(d_vals, [ak[d] for d in d_vals], color='#1d4ed8', lw=2.0, ls='--', label='AdjacentKey (typos, mid)')\n",
    "        ax.plot(d_vals, [period[d] for d in d_vals], color='#DD8452', lw=2.0, label='?→. (mild)')\n",
    "        ax.plot(d_vals, [slash[d]  for d in d_vals], color='#C44E52', lw=2.0, label='?→/ (severe)')\n",
    "        ax.axhline(0.10, color='#94a3b8', lw=1, ls='--', alpha=0.7, label='10% ref')\n",
    "        ax.set_xscale('log'); ax.set_yscale('log')\n",
    "        ax.set_xlim(1, D_MAX - 1); ax.set_ylim(0.05, 1.1)\n",
    "        ax.set_xlabel('Distance from perturbation site (tokens)')\n",
    "        ax.set_ylabel('Relative angular change')\n",
    "        ax.legend(framealpha=0.9, loc='upper right', fontsize=9)\n",
    "        ax.grid(True, which='major', alpha=0.25); ax.grid(True, which='minor', alpha=0.1)\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(FIGURES_DIR / 'fig_punct_decay.png', bbox_inches='tight')\n",
    "        plt.show()\n",
))

# ── Multi-model comparison (preload-only) ───────────────────────────────
cells.append(md(
    "## Multi-model comparison — preload-only\n",
    "\n",
    "Renders the cross-model figures from results dirs you point to. Loading three 8B\n",
    "models simultaneously is too heavy, so this section never goes into interactive\n",
    "mode — it just reads JSON.\n",
    "\n",
    "Each entry in `RESULTS_PATHS` is the **base results dir** for that model (the\n",
    "directory the canonical scripts wrote into when they ran). The notebook knows the\n",
    "per-model subpaths.\n",
))

cells.append(code(
    "# ── Multi-model comparison ──────────────────────────────────────────\n",
    "RESULTS_PATHS = {\n",
    "    'Llama-3.1-8B': RESULTS_DIR,                                 # llama subpaths under here\n",
    "    'Qwen3-8B':     RESULTS_DIR,                                 # qwen3_8b/ subpath under here\n",
    "    'Gemma-4-E4B':  RESULTS_DIR,                                 # gemma4_e4b/ subpath under here\n",
    "}\n",
    "# To compare runs from DIFFERENT machines, point each model at its own dir:\n",
    "# RESULTS_PATHS = {\n",
    "#     'Llama-3.1-8B': Path('/path/to/run_a/results'),\n",
    "#     'Qwen3-8B':     Path('/path/to/run_b/results'),\n",
    "#     'Gemma-4-E4B':  Path('/path/to/run_c/results'),\n",
    "# }\n",
    "\n",
    "MODEL_SUBPATHS = {\n",
    "    'Llama-3.1-8B': {'on_site': 'per_layer_same_pos_100/results.json',\n",
    "                     'decay':   'typo_decay_preamble_control/results.json'},\n",
    "    'Qwen3-8B':     {'on_site': 'qwen3_8b/per_layer_same_pos/results.json',\n",
    "                     'decay':   'qwen3_8b/long_decay/results.json'},\n",
    "    'Gemma-4-E4B':  {'on_site': 'gemma4_e4b/per_layer_same_pos/results.json',\n",
    "                     'decay':   'gemma4_e4b/long_decay/results.json'},\n",
    "}\n",
    "CHECKPOINT_LAYERS = {\n",
    "    'Llama-3.1-8B': [8, 16, 24, 31],\n",
    "    'Qwen3-8B':     [9, 18, 27, 35],\n",
    "    'Gemma-4-E4B':  [10, 21, 28, 29, 40, 41],\n",
    "}\n",
    "GEMMA_SLIDING = {28, 40}\n",
    "COLORS  = {'Llama-3.1-8B': '#2563eb', 'Qwen3-8B': '#16a34a', 'Gemma-4-E4B': '#dc2626'}\n",
    "MARKERS = {'Llama-3.1-8B': 'o',       'Qwen3-8B': 's',       'Gemma-4-E4B': '^'}\n",
    "\n",
    "# ── Cross-model on-site rotation (Figure 1) ─────────────────────────\n",
    "fig, ax = plt.subplots(figsize=(5.5, 4))\n",
    "shown = []\n",
    "for mname in ['Llama-3.1-8B', 'Qwen3-8B', 'Gemma-4-E4B']:\n",
    "    base = RESULTS_PATHS[mname]\n",
    "    data = load_json(base / MODEL_SUBPATHS[mname]['on_site'])\n",
    "    if data is None: continue\n",
    "    pl = data.get('per_layer') or data.get('per_layer_same_pos', {}).get('per_layer')\n",
    "    if pl is None: continue\n",
    "    total = n_layers(pl)\n",
    "    layers = CHECKPOINT_LAYERS[mname]\n",
    "    depth  = [round(L / (total - 1) * 100) for L in layers]\n",
    "    angles = [cos_to_deg(pl[str(L)]['same_pos_mean']) for L in layers]\n",
    "    stds   = [cos_std_to_deg_std(pl[str(L)]['same_pos_mean'], pl[str(L)]['same_pos_std']) for L in layers]\n",
    "    ax.plot(depth, angles, marker=MARKERS[mname], markersize=7, color=COLORS[mname], label=mname, linewidth=2)\n",
    "    ax.fill_between(depth, [a - s for a, s in zip(angles, stds)], [a + s for a, s in zip(angles, stds)],\n",
    "                    color=COLORS[mname], alpha=0.15)\n",
    "    if mname == 'Gemma-4-E4B':\n",
    "        for L, dp, ang in zip(layers, depth, angles):\n",
    "            if L in GEMMA_SLIDING:\n",
    "                ax.plot(dp, ang, marker=MARKERS[mname], markersize=9,\n",
    "                        markerfacecolor='white', markeredgecolor=COLORS[mname], markeredgewidth=2)\n",
    "    shown.append(mname)\n",
    "ax.set_xlabel('Layer depth (%)'); ax.set_ylabel('On-site angular change (°)')\n",
    "ax.set_ylim(20, 80); ax.set_title('Figure 1 — Cross-model on-site rotation')\n",
    "if shown: ax.legend()\n",
    "ax.grid(alpha=0.3); plt.tight_layout()\n",
    "plt.savefig(FIGURES_DIR / 'fig_onsite_crossmodel.png', bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'Figure 1: models shown = {shown}')\n",
    "\n",
    "# ── Cross-model spatial decay (Figure 2 + appendix) ─────────────────\n",
    "panels_data = []\n",
    "for mname in ['Llama-3.1-8B', 'Qwen3-8B', 'Gemma-4-E4B']:\n",
    "    base = RESULTS_PATHS[mname]\n",
    "    data = load_json(base / MODEL_SUBPATHS[mname]['decay'])\n",
    "    if data is not None:\n",
    "        panels_data.append((mname, data))\n",
    "\n",
    "if not panels_data:\n",
    "    print('No decay results to render.')\n",
    "else:\n",
    "    fig, axes = plt.subplots(1, len(panels_data), figsize=(5.5 * len(panels_data), 4), squeeze=False)\n",
    "    axes = axes[0]\n",
    "    PANEL_LAYERS = {\n",
    "        'Llama-3.1-8B': [('8', '#93c5fd'), ('16', '#3b82f6'), ('24', '#1d4ed8'), ('31', '#1e3a5f')],\n",
    "        'Qwen3-8B':     [('9', '#bbf7d0'), ('18', '#4ade80'), ('27', '#16a34a'), ('35', '#14532d')],\n",
    "        'Gemma-4-E4B':  [('10', '#fca5a5'), ('21', '#ef4444'), ('40', '#b91c1c'), ('41', '#7f1d1d')],\n",
    "    }\n",
    "    for ax, (mname, data) in zip(axes, panels_data):\n",
    "        # Llama uses preamble_control structure; Qwen3/Gemma use long_decay structure.\n",
    "        is_preamble = 'per_condition' in data\n",
    "        for lyr, color in PANEL_LAYERS[mname]:\n",
    "            if is_preamble:\n",
    "                conds = [c for c in ['early', 'mid', 'late'] if c in data['per_condition']]\n",
    "                d_vals = list(range(1, 31))\n",
    "                curves = []\n",
    "                for cond in conds:\n",
    "                    e = data['per_condition'][cond]['per_layer'].get(lyr)\n",
    "                    if e: curves.append([e['avg_rel_curve'][d] for d in d_vals])\n",
    "                if curves:\n",
    "                    ax.plot(d_vals, np.mean(curves, axis=0), color=color, lw=2.0, label=f'L{lyr}')\n",
    "            else:\n",
    "                # long_decay structure\n",
    "                curves = []\n",
    "                for bname, bd in data.items():\n",
    "                    if not isinstance(bd, dict): continue\n",
    "                    avg = bd.get('avg_angular') or bd.get('per_layer', {}).get(lyr, {}).get('avg_angular')\n",
    "                    if avg: curves.append(np.array(avg))\n",
    "                if not curves: continue\n",
    "                n_min = min(len(c) for c in curves)\n",
    "                rels = np.mean([(c[:n_min] / max(c[0], 1e-9)) for c in curves], axis=0)\n",
    "                ax.plot(range(1, n_min), rels[1:], color=color, lw=2.0, label=f'L{lyr}')\n",
    "        ax.axhline(0.10, color='#94a3b8', lw=1, ls='--', alpha=0.7, label='10% ref')\n",
    "        ax.set_xscale('log'); ax.set_yscale('log')\n",
    "        ax.set_xlim(1, 30); ax.set_ylim(0.03, 1.1)\n",
    "        ax.set_xlabel('Distance from typo (tokens)'); ax.set_ylabel('Relative angular change')\n",
    "        ax.set_title(mname); ax.legend(framealpha=0.9, fontsize=9, loc='upper right')\n",
    "        ax.grid(True, which='major', alpha=0.25); ax.grid(True, which='minor', alpha=0.1)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(FIGURES_DIR / 'fig_crossmodel_decay.png', bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Figure 2 + appendix: models shown = {[m for m, _ in panels_data]}')\n",
))


# ════════════════════════════════════════════════════════════════════════════
# Build
# ════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    write_nb('section_5.ipynb', cells)
